import './globals.css'
import NavBar from '@/components/Navbar/Navbar'
import Checkout from '@/components/Checkout/Checkout'
/* eslint-disable @next/next/no-page-custom-font */

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/logo.svg' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta name='description' content='Generated by create next app' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin='true' />
        <link href='https://fonts.googleapis.com/css2?family=Afacad:ital,wght@0,400;0,700;1,400;1,700&display=swap' rel='stylesheet' />
        <meta name='author' content='Chore' />
        <title>Coffee Shop</title>
      </head>

      <body
        className=' relative h-full antialiased'
      >
        <NavBar />
        <Checkout />

        {children}
      </body>
    </html>
  )
}
